apiVersion: plugin.krew.app/v1alpha1
kind: Plugin
metadata:
  name: ca-cert
spec:
  platforms:
  - head: https://github.com/ahmetb/kubectl-extras/archive/master.zip
    files:
    - from: "/ca-cert/*"
    selector:
      matchExpressions:
      - {key: os, operator: In, values: [darwin, linux]}
  version: "master"
  intro: Print PEM CA certificate of current cluster 

