apiVersion: plugin.krew.app/v1alpha1
kind: Plugin
metadata:
  name: gke-ui
spec:
  platforms:
  - head: https://github.com/ahmetb/kubectl-extras/archive/master.zip
    files:
    - from: "/gke-ui/*"
      to: "."
    selector:
      matchExpressions:
      - {key: os, operator: In, values: [darwin, linux]}
  version: "master"
  intro: Launch GKE web interface

