apiVersion: plugin.krew.app/v1alpha1
kind: Plugin
metadata:
  name: krew
spec:
  platforms:
  - uri: https://storage.googleapis.com/krew-test/krew-e7166676ae3bfe2eb750283c9d800d85f0e1b36b97edbc840a3e5b494e6bb29f.zip
    sha256: e7166676ae3bfe2eb750283c9d800d85f0e1b36b97edbc840a3e5b494e6bb29f
    files:
    - from: "unix/plugin.yaml"
      to: plugin.yaml
    - from: "krew-darwin"
      to: "krew"
    - from: "unix/commands/*"
      to: "commands"
    selector:
      matchExpressions:
      - {key: os, operator: In, values: [darwin]}
  - uri: https://storage.googleapis.com/krew-test/krew-e7166676ae3bfe2eb750283c9d800d85f0e1b36b97edbc840a3e5b494e6bb29f.zip
    sha256: e7166676ae3bfe2eb750283c9d800d85f0e1b36b97edbc840a3e5b494e6bb29f
    files:
    - from: "unix/plugin.yaml"
      to: plugin.yaml
    - from: "krew-linux"
      to: "krew"
    - from: "unix/commands/*"
      to: "commands"
    selector:
      matchExpressions:
      - {key: os, operator: In, values: [linux]}
  - uri: https://storage.googleapis.com/krew-test/krew-e7166676ae3bfe2eb750283c9d800d85f0e1b36b97edbc840a3e5b494e6bb29f.zip
    sha256: e7166676ae3bfe2eb750283c9d800d85f0e1b36b97edbc840a3e5b494e6bb29f
    files:
    - from: "windows/plugin.yaml"
      to: plugin.yaml
    - from: "krew-windows.exe"
      to: "krew.exe"
    - from: "windows/commands/*"
      to: "commands"
    selector:
      matchExpressions:
      - {key: os, operator: In, values: [windows]}
  version: "v0.0.1"
  intro: Install plugins
