apiVersion: plugin.krew.app/v1alpha1
kind: Plugin
metadata:
  name: krew
spec:
  platforms:
  - uri: https://storage.googleapis.com/krew-test/krew.zip
    sha256: aca61bfe2fd2c188e71331f5929606572ab28037b1669b7141ef94e55400d9f7
    files:
    - from: "/commands/*"
      to: "commands"
    - from: "plugin.yaml"
    - from: "krew-darwin"
      to: "krew"
    selector:
      matchExpressions:
      - {key: os, operator: In, values: [darwin]}
  - uri: https://storage.googleapis.com/krew-test/krew.zip
    sha256: aca61bfe2fd2c188e71331f5929606572ab28037b1669b7141ef94e55400d9f7
    files:
    - from: "/commands/*"
      to: "commands"
    - from: "plugin.yaml"
    - from: "krew-linux"
      to: "krew"
    selector:
      matchExpressions:
      - {key: os, operator: In, values: [linux]}
  version: "v0.0.1"
  intro: Install plugins
