apiVersion: plugin.krew.app/v1alpha1
kind: Plugin
metadata:
  name: krew
spec:
  platforms:
  - uri: https://storage.googleapis.com/krew-test/krew.zip
    sha256: 1076f3c6c22db679762cc447598cc8bb1769047f72187c567d42b949c642696f
    files:
    - from: "/*"
    selector:
      matchExpressions:
      - {key: os, operator: In, values: [darwin]}
  version: "v0.0.1"
  intro: Install plugins
