apiVersion: plugin.krew.app/v1alpha1
kind: Plugin
metadata:
  name: krew
spec:
  platforms:
  - uri: https://storage.googleapis.com/krew-test/krew.zip
    sha256: 48d853fd7bbe8ea07b56a0ec4dfcbb355723f4ed1a2eeb31bb6b818810d84b6f
    files:
    - from: "plugin.yaml"
    - from: "krew-darwin"
      to: "krew"
    - from: "/commands/*"
      to: "commands"
    selector:
      matchExpressions:
      - {key: os, operator: In, values: [darwin]}
  - uri: https://storage.googleapis.com/krew-test/krew.zip
    sha256: 48d853fd7bbe8ea07b56a0ec4dfcbb355723f4ed1a2eeb31bb6b818810d84b6f
    files:
    - from: "plugin.yaml"
    - from: "krew-linux"
      to: "krew"
    - from: "/commands/*"
      to: "commands"
    selector:
      matchExpressions:
      - {key: os, operator: In, values: [linux]}
  version: "v0.0.1"
  intro: Install plugins
