apiVersion: plugin.krew.app/v1alpha1
kind: Plugin
metadata:
  name: krew
spec:
  platforms:
  - uri: https://storage.googleapis.com/krew-test/krew.zip
    sha256: 531ff2dc4eca840268e3e9947f2fc41ccf72b4f734d6700a25abf6b4b125b91e
    files:
    - from: "/*"
    selector:
      matchExpressions:
      - {key: os, operator: In, values: [darwin]}
  version: "v0.0.1"
  intro: Install plugins
