apiVersion: plugin.krew.app/v1alpha1
kind: Plugin
metadata:
  name: krew
spec:
  platforms:
  - uri: https://storage.googleapis.com/krew-test/krew-8f075d1d27a4e0795b7b8b448be9b3cb628f5b1d037706094f55ad0ea90ca3b0.zip
    sha256: 8f075d1d27a4e0795b7b8b448be9b3cb628f5b1d037706094f55ad0ea90ca3b0
    files:
    - from: "unix/plugin.yaml"
      to: plugin.yaml
    - from: "krew-darwin"
      to: "krew"
    - from: "unix/commands/*"
      to: "commands"
    selector:
      matchExpressions:
      - {key: os, operator: In, values: [darwin]}
  - uri: https://storage.googleapis.com/krew-test/krew-8f075d1d27a4e0795b7b8b448be9b3cb628f5b1d037706094f55ad0ea90ca3b0.zip
    sha256: 8f075d1d27a4e0795b7b8b448be9b3cb628f5b1d037706094f55ad0ea90ca3b0
    files:
    - from: "unix/plugin.yaml"
      to: plugin.yaml
    - from: "krew-linux"
      to: "krew"
    - from: "unix/commands/*"
      to: "commands"
    selector:
      matchExpressions:
      - {key: os, operator: In, values: [linux]}
  - uri: https://storage.googleapis.com/krew-test/krew-8f075d1d27a4e0795b7b8b448be9b3cb628f5b1d037706094f55ad0ea90ca3b0.zip
    sha256: 8f075d1d27a4e0795b7b8b448be9b3cb628f5b1d037706094f55ad0ea90ca3b0
    files:
    - from: "windows/plugin.yaml"
      to: plugin.yaml
    - from: "krew-windows.exe"
      to: "krew.exe"
    - from: "windows/commands/*"
      to: "commands"
    selector:
      matchExpressions:
      - {key: os, operator: In, values: [windows]}
  version: "v0.0.1"
  intro: Install plugins
