apiVersion: plugin.krew.app/v1alpha1
kind: Plugin
metadata:
  name: krew
spec:
  platforms:
  - uri: https://storage.googleapis.com/krew-test/krew-9fdfb3b93148dd1865841462b3166f53e2bd3c96517c5599ca45dee60c1acc68.zip
    sha256: 9fdfb3b93148dd1865841462b3166f53e2bd3c96517c5599ca45dee60c1acc68
    files:
    - from: "unix/plugin.yaml"
      to: plugin.yaml
    - from: "krew-darwin"
      to: "krew"
    - from: "unix/commands/*"
      to: "commands"
    selector:
      matchExpressions:
      - {key: os, operator: In, values: [darwin]}
  - uri: https://storage.googleapis.com/krew-test/krew-9fdfb3b93148dd1865841462b3166f53e2bd3c96517c5599ca45dee60c1acc68.zip
    sha256: 9fdfb3b93148dd1865841462b3166f53e2bd3c96517c5599ca45dee60c1acc68
    files:
    - from: "unix/plugin.yaml"
      to: plugin.yaml
    - from: "krew-linux"
      to: "krew"
    - from: "unix/commands/*"
      to: "commands"
    selector:
      matchExpressions:
      - {key: os, operator: In, values: [linux]}
  - uri: https://storage.googleapis.com/krew-test/krew-9fdfb3b93148dd1865841462b3166f53e2bd3c96517c5599ca45dee60c1acc68.zip
    sha256: 9fdfb3b93148dd1865841462b3166f53e2bd3c96517c5599ca45dee60c1acc68
    files:
    - from: "windows/plugin.yaml"
      to: plugin.yaml
    - from: "krew-windows.exe"
      to: "krew.exe"
    - from: "windows/commands/*"
      to: "commands"
    selector:
      matchExpressions:
      - {key: os, operator: In, values: [windows]}
  version: "v0.0.1"
  intro: Install plugins
