apiVersion: plugin.krew.app/v1alpha1
kind: Plugin
metadata:
  name: krew
spec:
  platforms:
  - uri: https://storage.googleapis.com/krew-test/krew.zip
    sha256: 97c846dc8b92924e83c2d97e4d88c8cb0e8284bdf759a4888a9d8193ad6e2ba3
    files:
    - from: "/*"
    selector:
      matchExpressions:
      - {key: os, operator: In, values: [darwin]}
  version: "v0.0.1"
  intro: Install plugins

