apiVersion: plugin.krew.app/v1alpha1
kind: Plugin
metadata:
  name: mtail
spec:
  platforms:
  - head: https://github.com/ahmetb/kubectl-extras/archive/master.zip
    files:
    - from: "/mtail/*"
      to: "."
    selector:
      matchExpressions:
      - {key: os, operator: In, values: [darwin, linux]}
  version: "master"
  intro: Tail logs from multiple pods matching label selector
  caveats: |
    This plugin needs the following programs:
    * jq
