apiVersion: plugin.krew.app/v1alpha1
kind: Plugin
metadata:
  name: refresh-tokens
spec:
  platforms:
  - head: https://github.com/ahmetb/kubectl-extras/archive/master.zip
    files:
    - from: "/refresh-tokens/*"
    selector:
      matchExpressions:
      - {key: os, operator: In, values: [darwin, linux]}
  version: "master"
  intro: Make a call to all clusters in kubeconfig to refresh access tokens

