apiVersion: plugin.krew.app/v1alpha1
kind: Plugin
metadata:
  name: view-secret
spec:
  platforms:
  - head: https://github.com/ahmetb/kubectl-extras/archive/master.zip
    files:
    - from: "/view-secret/*"
    selector:
      matchExpressions:
      - {key: os, operator: In, values: [darwin, linux]}
  version: "master"
  intro: Decode secrets

